version: 0.2
env:
  variables:
    AWS_DEFAULT_REGION: "eu-west-1"
    IMAGE_TAG: "latest"
phases:
  install:
    runtime-versions:
      java: corretto11
  pre_build:
    commands:
  build:
    commands:
      - mvn clean install
cache:
  paths:
    - '/root/.m2/**/*'
#artifacts:
  #files:
    #- imagedefinitions.json
  #discard-paths: yes

reports:
  REPORT:
    files:
      - 'cucumber-html-reports'
      - 'overview-failures.html'
      - 'karate.log'
    file-format: CUCUMBERJSON
    base-directory: 'target/'
